application/src/main/webapp/js/chat-modules.js, application/src/main/webapp/js/chat.js
This PR adds the following behaviors :
* when the scroll is at the bottom of a room (last message shown) and a new message is received, the new message is displayed
* when the scroll is not at the bottom of a room and a new message is received, the scroll does not move and the new message is not shown
* when switching from one room to another one, always scroll down to the last message
This fix has been tested on Chrome and Firefox, but not yet on IE/Edge. If a reviewer can do that for me, I'll owe him/her a beer ;-)
=> CHAT-369 : do not scroll down to bottom automaticaly when scrolling the messages

application/src/main/webapp/js/chat.js
The room is loaded on 2 events : when clicking on the name of the room in the menu and when clicking on the menu line in the menu. Since the room name is inside the menu line, the 2 events are triggered, so the room is loaded 2 times.
This PR removes the load when clicking on the room's name.
=> CHAT-378 : do not load room when clicking on the room's name in the menu

application/src/main/webapp/js/chat-modules.js, application/src/main/webapp/js/chat.js
I frequently need to edit my last message to fix the spelling or change some wording. Currently we need to use the mouse to go on the chat line + clic on the right action and this is painful and a wast of focus.
What I have done / changed is : 
* from the chat message box, press the UP arrow to edit your LAST message
* the text-area in the edit box have the focus to be ready to write
* when the edited message is saved (clic on save button or press ENTER) the focus is set on the chat message box
* when we cancel or press on escape key from the text-area in the edit box, the focus is now set on the chat message box
=> CHAT-379 : edit my last message by pressing the UP arrow

application/src/main/java/org/exoplatform/chat/portlet/notification/package-info.java, application/src/main/webapp/js/chat.js, application/src/main/webapp/js/jquery-juzu-utils-0.2.0.js
I fixed this issue in a simpler manner to avoid too big refactoring or the use of another third party library (like https://github.com/mathiasbynens/he).
I renamed the `jquery-juzu-utils-0.1.0.js` to avoid the need of browser refresh for the end user.
This fix correctly decode the following characters in the Team Room label : 
* `&amp;` => `&`
* `&gt;` => `>`
* `&lt;` => `<`
=> CHAT-368 : decode Rooms labels on the room list

pom.xml, server/src/main/java/org/exoplatform/chat/services/mongodb/ChatServiceImpl.java, server/src/main/java/org/exoplatform/chat/services/mongodb/MongoBootstrap.java
This PR upgrades to Java driver 3.2. It replaces the deprecated Mongo client class by the new one MongoClient.
I have a doubt about authentication mechanism. It has changed since 3.0 in the Java driver. Now the authentication credentials must be passed at the creation of the MongoClient object, whereas it was done on db fetch in the previous versions.
=> CHAT-345 : upgrade java driver to 3.2

server/src/main/java/org/exoplatform/chat/services/mongodb/MongoBootstrap.java
This PR removes indexes on timestamp only since they are not used, and adds a new index on roomId and timestamp.
=> CHAT-388 : remove indexes on timestamp only and add a new index on roomId and timestamp

application/src/main/webapp/js/chat-modules.js
This PR add a chek on the message type. If it is defined, the message is displayed. This is the case for meeting start and end messages.
=> CHAT-420 : display message when message content is empty but type is defined (case of meeting start and end messages)

application/src/main/java/org/exoplatform/chat/portlet/chat/assets/responsive-400px-max.less, application/src/main/java/org/exoplatform/chat/portlet/chat/assets/responsive-767px-max.less
This PR implements a basic responsive version of the chat-application for smartphones :
* the message panel is moved under the rooms list
* the panels use the full width of the screen
* in portrait orientation, timestamp of a message is displayed above the message text to leave space for the text
* in portrait orientation, actions on messages (save notes, edit, ...) are not available
=> CHAT-430 : basic responsive version for smartphones

application/src/main/webapp/js/chat-modules.js, application/src/main/webapp/js/chat.js
This PR avoids the blink effect on room users panel when not emptying the html before updating it. It also improves the update by checking if there have been changes in the users list and updates the DOM only it there have been changes.
=> CHAT-463 : do not empty the html of the room users panel before updating it + update the panel only if there were changes in the room users list

application/src/main/webapp/js/notif.js, server/src/main/java/org/exoplatform/chat/model/NotificationBean.java, server/src/main/java/org/exoplatform/chat/model/RoomBean.java, server/src/main/java/org/exoplatform/chat/services/mongodb/NotificationServiceImpl.java, server/src/main/java/org/exoplatform/chat/services/mongodb/UserServiceImpl.java
Instead of harcoding the target room as a team room, the room type is now read to set the right target room identifier.
=> CHAT-507 : set the right target room to load it correctly and hide the right panel in case of 1:1 rooms

application/src/main/webapp/js/chat.js
This PR :
* hides the admin actions in the drop down menu as soon as a room is loaded to make sure admin actions are not visible by anyone, even temporarily
* removes the reset of the room creator when loading room users since it is useless and prevents from displaying the room edition popup
=> CHAT-563 : Cannot edit a room

application/src/main/java/org/exoplatform/chat/portlet/chat/assets/base.less, application/src/main/java/org/exoplatform/chat/portlet/chat/templates/index.gtmpl
This PR removes the space between the input field and the suggestion list and change the width of the suggestion list. I change the min-width of this list to match with the input field, but I kept the variable width since I think it is better to not cut long user names.
=> CHAT-559 : remove space between input field and suggetion list + improve suggestion list width

application/src/main/java/org/exoplatform/chat/portlet/notification/NotificationApplication.java, application/src/main/java/org/exoplatform/chat/portlet/notification/templates/index.gtmpl, application/src/main/webapp/js/chat-modules.js, application/src/main/webapp/js/notif.js, server/src/main/java/org/exoplatform/chat/utils/PropertyManager.java
Increase default polling intervals to reduce server load.
Sample configuration files have already been changed in https://github.com/exo-addons/chat-application/commit/4a894ee6095365063dc360a8e0e84033891884b8.
=> CHAT-582 : increase default polling intervals to reduce server load

server/src/main/java/org/exoplatform/chat/services/mongodb/UserMongoDataStorage.java, server/src/test/java/org/exoplatform/chat/ChatTestCase.java
Return null in the API when the fetched room does not exist instead of returning an empty object.
=> CHAT-711 : return null in the API when the fetched room does not exist

application/src/main/webapp/js/chat.js, application/src/main/webapp/js/notif.js
Only status indicators of the current user where updated before. With this PR, any status indicator on the page are updated if they are related to the incoming websocket event.
When I say "any", it is actually the known one, which are the one in the menu of the profile page and the one in the profile page (below the menu).
The ugly thing about this IMO is that we have to target specifically these indicator, meaning it is totally coupled with the DOM and css classes used in Profile portlets. We should instead have a common UI component for the user status, and the user status should probably be managed in PLF (not only chat). But that's another story ;-)
=> SOC-5908 : update all status indicators on the profile page

application/src/main/webapp/js/chat.js
When editing a message, the HTML content is updated but not the messages variable. Since CHAT-763, the edited message is taken from the messages variables (to avoid encoding issues). This PR updates the messages variable after a message has been updated.
=> CHAT-785 : update the message in memory after being edited to keep it sync between memory and display

application/src/main/java/org/exoplatform/chat/portlet/notification/NotificationApplication.java
The issue is a regression of https://jira.exoplatform.org/browse/CHAT-782 which used the space pretty name instead of the space id. The room is fetched via its id, so this PR change it back to space id.
=> CHAT-788 : use space id instead of space pretty name to get the space room

application/src/main/webapp/js/chat.js, application/src/main/webapp/js/chatRoom.js
When a message is updated, the local list in memory is updated correctly but not the one in receivers' browsers. This PR updates the list in the updateMessage method to be sure it is well done in all cases.
=> CHAT-803 : update message in memory when a message is updated

common/src/main/java/org/exoplatform/chat/services/TokenService.java, server-embedded/src/main/java/org/exoplatform/chat/server/ChatTools.java, server-embedded/src/main/java/org/exoplatform/chat/services/TokenServiceImpl.java, server-embedded/src/main/java/org/exoplatform/chat/services/TokenStorage.java, server-embedded/src/main/java/org/exoplatform/chat/services/mongodb/TokenMongoService.java, services/src/main/java/org/exoplatform/addons/chat/listener/ServerBootstrap.java, services/src/main/java/org/exoplatform/addons/chat/listener/UpdateUserStatusListener.java
When a user does a logout, the listener org.exoplatform.addons.chat.listener.UpdateUserStatusListener did a complete removalof the user object in the database.
This user object contains the user information and the list of his team rooms and favorites.
Then at the next login, the user is recreated, but without any room or favorite.
This fix only clear the user token (to keep the fix for CHAT-787), not the whole user object.
=> CHAT-814 : remove only user token on logout, not the whole user object

application/src/main/webapp/js/chatRoom.js
When an user posts a message, it is first added in the room (client side) and then received via websocket from the server (with additional information). When it is received from the server, we check in the list of messages in memory to update it with the new version of the message received fro the server (based on the clientId).
The wrong id was used when updating the list of messages by the message received from the server, so the list was not updated. And in such a case, it considered it as a new message and displayed it again.
This fix uses the right id to update the list (updatedMessage.msgId).
Also, in the addMessage, the check is now done on msg.clientId instead of msg.msgId to know if it is a new message. Previously this check wasdone on msg.msgId (which existed) and then a search …
=> CHAT-822 : display messages only once

application/src/main/webapp/js/chat.js, application/src/main/webapp/js/chatCometd3.js, application/src/main/webapp/js/notif.js
Even if the websocket connection is explicitly disconnected, when sending the next message the connection is automatically re-established.
This fix prevent this automatic reconnection is the disconnection has been explicitly requested. It always clear the credentials for more security.
=> CHAT-825 : avoid automatic reconnection of websocket connection if it has been explicitly disconnected

application/src/main/webapp/css/chatMobile.less
The chat notification menu is not well displayed on mobile. So I added to the drop-down menu "left" and "right" css properties to adjust its position.
I tried to adjust the width, but the drop-down menu contains fixed items about the user status in chat. It will add some white space that may affect display ergonomics.
Tested on: platform-5.2.x-edit-activities-comments-SNAPSHOT
=> MOB-2198: Adjust chat notification menu position
